export const experienceTimeline = [
  {
    company: 'NeoSOFT',
    role: 'Lead Full-Stack .NET Developer & Scrum Facilitator',
    period: '01/2026 – Present',
    focus: 'Musafir JETT Visa Platform',
    details: [
      'Distributed cloud microservices for the Musafir JETT Visa Platform.',
      'Platform handled 2M+ leads and 30M+ operations.',
      'Led 8+ software engineers.',
      'Facilitated Daily Scrum, Sprint Planning, and Sprint Retrospectives.',
      'Used .NET 8 and CQRS to decouple legacy modules.',
      'Worked with Azure, Docker, and RabbitMQ.',
      'Improved asynchronous processing throughput by 25%.',
      'Implemented SonarQube validation pipelines.',
      'Maintained zero-vulnerability quality gates.',
    ],
  },
  {
    company: 'Vaibhav Global Ltd',
    role: 'Senior Full-Stack .NET Developer / Architecture Lead',
    period: '01/2024 – 12/2025',
    focus: 'Enterprise e-commerce platform',
    details: [
      'Application refactoring and query optimization.',
      'Improved API throughput by 40%.',
      'Reduced response delays by 120ms.',
      'Database optimization and advanced caching.',
      'Reduced index fragmentation by 35%.',
      'Handled task allocation and sprint-based capacity planning.',
    ],
  },
  {
    company: 'GlobalLogic',
    role: 'Full-Stack .NET Developer / Module Lead',
    period: '01/2021 – 12/2024',
    focus: 'Academic management modules',
    details: [
      'Worked on academic management modules.',
      'Applied Clean Architecture in multiple legacy environments.',
      'Used Angular, Dapper, and xUnit.',
      'Improved execution efficiency by 35%.',
      'Reduced payload round-trip latency by 20%.',
      'Worked closely with Product Owners and stakeholders.',
      'Managed sprint backlog and clarified requirements.',
    ],
  },
  {
    company: 'Chetu India',
    role: 'Full-Stack .NET Developer',
    period: '01/2019 – 12/2021',
    focus: 'Enterprise Healthcare IT systems',
    details: [
      'Worked on enterprise healthcare IT systems.',
      'Built secure backend modules aligned with OWASP Top 10.',
      'Used Azure DevOps, Docker, and CI/CD practices.',
      'Reduced deployment schedules by 70%.',
    ],
  },
  {
    company: 'Unit One Solution',
    role: 'Software Developer',
    period: '01/2017 – 12/2019',
    focus: 'Collage ERP application',
    details: [
      'Worked on a collage ERP application using ASP.NET MVC.',
      'Delivered modular business logic.',
      'Optimized database communication latency by 25%.',
    ],
  },
];
